import matplotlib.pylab as plt
import numpy as np

datos=np.loadtxt("datosE.dat")
datos1=np.loadtxt("datosRK.dat")
datos2=np.loadtxt("datosRK2.dat")
datos3=np.loadtxt("datosRK3.dat")
datos4=np.loadtxt("datosRK4.dat")
plt.figure()
plt.plot(datos[:,0],datos[:,1])
plt.plot(datos[:,0],datos[:,2])
plt.title("Euler")
plt.xlabel("Tiempo")
plt.ylabel("Valor")
plt.savefig("Euler.png")
plt.figure()
plt.plot(datos1[:,0],datos1[:,1])
plt.plot(datos1[:,0],datos1[:,2])
plt.xlabel("Tiempo")
plt.ylabel("Valor")
plt.title("Rk4")
plt.savefig("RK4.png")
plt.figure()
plt.plot(datos[:,0],datos[:,1])
plt.plot(datos1[:,0],datos1[:,1])
plt.title("Comparación y0")
plt.xlabel("Tiempo")
plt.ylabel("Valor")
plt.savefig("Comp1.png")
plt.figure()
plt.plot(datos[:,0],datos[:,2])
plt.plot(datos1[:,0],datos1[:,2])
plt.title("Comparación y1")
plt.xlabel("Tiempo")
plt.ylabel("Valor")
plt.savefig("Comp2.png")
plt.figure()
plt.plot(datos[:,1],datos[:,2])
plt.title("Euler y0 vs y1")
plt.xlabel("Tiempo")
plt.ylabel("Valor")
plt.savefig("Ey0vsy1.png")
plt.figure()
plt.plot(datos1[:,1],datos1[:,2])
plt.title("RK4 y0 vs y1")
plt.xlabel("Tiempo")
plt.ylabel("Valor")
plt.savefig("Ry0vsy1.png")
plt.figure()
plt.plot(datos1[:,1],datos1[:,2])
plt.plot(datos2[:,1],datos2[:,2])
plt.plot(datos3[:,1],datos3[:,2])
plt.plot(datos4[:,1],datos4[:,2])
plt.title("Cambios de lamda")
plt.xlabel("Tiempo")
plt.ylabel("Valor")
plt.savefig("lambda.png")
